### ISSUE TITLE
Issue while loading model, "en_core_web_lg-sprl"

### ISSUE THREAD

**Issue by GargiVyas31** [mmxgn/sprl-spacy#2]
When I try to load this model, I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gargi/.local/lib/python3.6/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/gargi/.local/lib/python3.6/site-packages/spacy/util.py", line 217, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/home/gargi/.local/lib/python3.6/site-packages/spacy/util.py", line 262, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/gargi/.local/lib/python3.6/site-packages/spacy/language.py", line 940, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/gargi/.local/lib/python3.6/site-packages/spacy/util.py", line 733, in from_disk
    reader(path / key)
  File "/home/gargi/.local/lib/python3.6/site-packages/spacy/language.py", line 927, in <lambda>
    p, exclude=["vocab"]
  File "tokenizer.pyx", line 450, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 496, in spacy.tokenizer.Tokenizer.from_bytes
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 527, in _parse
    code1 = _class_escape(source, this)
  File "/usr/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 275

**Comment by mmxgn** [comment]
Hi, thanks for the issue report.

What version of Spacy are you using?

**Comment by GargiVyas31** [comment]
H, I am using spaCy version 2.2.2

**Comment by mmxgn** [comment]
Seems it is an issue with Spacy versions >2.0.18.

If it is ok with you you can install a compatible spacy version with 

```
pip install spacy==2.0.18
```

In the meantime I have done work updating it to better models with Flair and the complete SpRL dataset which I need to fix and update the code with.

**Comment by djinit-ai** [comment]
Yes, that works. 
Thank You

**Comment by mmxgn** [comment]
Great, closing the issue
